//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFM.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResultCode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResultCode() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DFM.Shared.Resources.ResultCode", typeof(ResultCode).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized has been failured please try again.
        /// </summary>
        public static string AUTH_FAILED {
            get {
                return ResourceManager.GetString("AUTH_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bucket Created.
        /// </summary>
        public static string BUCKET_CREATED {
            get {
                return ResourceManager.GetString("BUCKET_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bucket name could not empty.
        /// </summary>
        public static string BUCKET_EMPTY {
            get {
                return ResourceManager.GetString("BUCKET_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This bucket is already exist.
        /// </summary>
        public static string BUCKET_EXIST {
            get {
                return ResourceManager.GetString("BUCKET_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bucket could not found.
        /// </summary>
        public static string BUCKET_NOT_EXIST {
            get {
                return ResourceManager.GetString("BUCKET_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File content could not empty.
        /// </summary>
        public static string CONTENT_EMPTY {
            get {
                return ResourceManager.GetString("CONTENT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content is empty.
        /// </summary>
        public static string CONTENT_IS_EMPTY {
            get {
                return ResourceManager.GetString("CONTENT_IS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create record.
        /// </summary>
        public static string COULD_NOT_CREATE_RECORD {
            get {
                return ResourceManager.GetString("COULD_NOT_CREATE_RECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update record.
        /// </summary>
        public static string COULD_NOT_UPDATE_RECORD {
            get {
                return ResourceManager.GetString("COULD_NOT_UPDATE_RECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role could not dupplicate.
        /// </summary>
        public static string DUPPLICATE_ROLE {
            get {
                return ResourceManager.GetString("DUPPLICATE_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ID should not empty.
        /// </summary>
        public static string EMPTY_ID {
            get {
                return ResourceManager.GetString("EMPTY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name could not empty.
        /// </summary>
        public static string FILENAME_EMPTY {
            get {
                return ResourceManager.GetString("FILENAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid grant_type.
        /// </summary>
        public static string GRANT_INVALID {
            get {
                return ResourceManager.GetString("GRANT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not list document, invalid link.
        /// </summary>
        public static string INVALID_LINK {
            get {
                return ResourceManager.GetString("INVALID_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid signature from client, please verify signature before call API.
        /// </summary>
        public static string INVALID_SIGNATURE {
            get {
                return ResourceManager.GetString("INVALID_SIGNATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserID could not found from access token.
        /// </summary>
        public static string INVALID_USER {
            get {
                return ResourceManager.GetString("INVALID_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New document created.
        /// </summary>
        public static string NEW_DOCUMENT {
            get {
                return ResourceManager.GetString("NEW_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No certificate found.
        /// </summary>
        public static string NO_CERT_FOUND {
            get {
                return ResourceManager.GetString("NO_CERT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client has no permit to access to API.
        /// </summary>
        public static string NO_PERMITTED {
            get {
                return ResourceManager.GetString("NO_PERMITTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data inquiry not found.
        /// </summary>
        public static string NOT_FOUND {
            get {
                return ResourceManager.GetString("NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Removed.
        /// </summary>
        public static string OBJECT_REMOVED {
            get {
                return ResourceManager.GetString("OBJECT_REMOVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Uploaded.
        /// </summary>
        public static string OBJECT_UPLOADED {
            get {
                return ResourceManager.GetString("OBJECT_UPLOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request failed parameter is empty.
        /// </summary>
        public static string PARAMETER_EMPTY {
            get {
                return ResourceManager.GetString("PARAMETER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register new user on Identity Server.
        /// </summary>
        public static string REG_USER_FAIL {
            get {
                return ResourceManager.GetString("REG_USER_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove object.
        /// </summary>
        public static string REMOVED_FAILED {
            get {
                return ResourceManager.GetString("REMOVED_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request failed.
        /// </summary>
        public static string REQUEST_FAIL {
            get {
                return ResourceManager.GetString("REQUEST_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not request token.
        /// </summary>
        public static string REQUEST_TOKEN_ERROR {
            get {
                return ResourceManager.GetString("REQUEST_TOKEN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string SUCCESS_OPERATION {
            get {
                return ResourceManager.GetString("SUCCESS_OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction ID not found .
        /// </summary>
        public static string TX_NOT_FOUND {
            get {
                return ResourceManager.GetString("TX_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserID could not empty.
        /// </summary>
        public static string USERID_EMPTY {
            get {
                return ResourceManager.GetString("USERID_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username could not empty.
        /// </summary>
        public static string USERNAME_COULD_NOT_EMPTY {
            get {
                return ResourceManager.GetString("USERNAME_COULD_NOT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username not found.
        /// </summary>
        public static string USERNAME_NOT_FOUND {
            get {
                return ResourceManager.GetString("USERNAME_NOT_FOUND", resourceCulture);
            }
        }
    }
}
