version: '3.4'

services:
  dfm.api:
    image: codecamplao/dfm-api:1.0.0
    restart: always
    ports:
      - "8081:80"
    environment:
      - TZ=Asia/Vientiane
    networks:
      - dfmnetwork

  dfm.frontend:
    image: codecamplao/dfm-frontend
    restart: always
    ports:
      - "8080:80"
    environment:
      - TZ=Asia/Vientiane
    networks:
      - dfmnetwork
    depends_on:
      - dfm.api

networks: 
  dfmnetwork:
    driver: bridge

  



